### ISSUE TITLE
Personalization Semantics Content Module 2020-01-27

### ISSUE THREAD

**Issue by clapierre** [w3c/i18n-request#109]
Note that the i18n WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://www.w3.org/International/review-request#selfreview.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: 
Personalization Semantics Content Module 1.0

- URL of spec: 
https://www.w3.org/TR/personalization-semantics-content-1.0/

- Do you need a reply by a particular date? 
No specific date although after our wide review we are planning on moving this to CR.

- Any information arising from a self-review? 

 If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),
Answer: N/A.

  If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.

Answer: We are using numerical tokens which can be mapped to symbols sets, so we don't think this is an issue but request you look at this closer. Also the symbol sets themselves may be localized.
[Spec symbol](https://www.w3.org/TR/personalization-semantics-content-1.0/#symbol-explanation)

  If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.

Answer: Simplification allows for replacing sections of text with an alternative text, which the author will provide.
[Simplification](https://www.w3.org/TR/personalization-semantics-content-1.0/#simplification-explanation)

  If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers
Answer: N/A

  If the spec (or its implementation) sorts text
Answer: N/A

  If the spec (or its implementation) captures user input
Answer: N/A

  If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries
Answer: N/A

  If the spec (or its implementation) allows any character encoding other than UTF-8.

Answer: We support UTF-8 but we anticipates supporting UTF-16 for symbol sets and there is nothing in our spec that would prevent this.

  If the spec (or its implementation) defines markup.

Answer:We do define attribute names and values as tokens that are human readable but we don't expect those to be localized. However we do have content simplification that does have alternative text descriptions.
[Simplification](https://www.w3.org/TR/personalization-semantics-content-1.0/#simplification-explanation)

  If the spec (or its implementation) deals with names, addresses, time & date formats, etc
Answer:data-purpose attribute does pattern after autocomplete attribute of HTML5 and author is responsible for any internationalization concerns.

  If the spec (or its implementation) describes a format or data that is likely to need localization.

Answer: data-purpose attribute does pattern after autocomplete attribute of HTML5 and author is responsible for any internationalization concerns.

  If the spec (or its implementation) makes any reference to or relies on any cultural norms

Answer: there are internationalized AAC symbol sets to address that concern. and we are supporting those translations

- Where and how to file issues arising? 

Feel free to raise issues on our Github Repo
https://github.com/w3c/personalization-semantics/issues

- Pointer to any explainer for the spec? 

Here is a link to our explainer document which may help for context.
[Personalization Semantics Explainer 1.0](https://www.w3.org/TR/personalization-semantics-1.0/)

Other comments:
None

**Comment by r12a** [comment]
Moved this request to a new issue at https://github.com/w3c/i18n-request/issues/110 which points back to the requesting WG repository.
