### ISSUE TITLE
Scalable Video Coding (SVC) Extension for WebRTC 2020-04-08 > 2020-05-08

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/i18n-request#112]
- name of spec to be reviewed: Scalable Video Coding (SVC) Extension for WebRTC
- URL of spec: https://www.w3.org/TR/2020/WD-webrtc-svc-20200408/

- What and when is your next expected transition? 
to CR, possibly a month from now
- What has changed since any previous review? 
N/A
- Any information arising from a self-review? 
The spec has a priori no I18N intersection
- Where and how to file issues arising? 
https://github.com/w3c/webrtc-svc/issues
- Pointer to any explainer for the spec? 
https://github.com/w3c/webrtc-svc/blob/master/explainer.md

Other comments:

**Comment by xfq** [comment]
I have reviewed the spec and didn't find any:

* natural language text that would be read/searched by a user
* issues regarding character encoding
* markup elements/attributes
* local date/time/format

-----

Filed https://github.com/w3c/i18n-activity/issues/884 as an editorial issue (it hasn't been reviewed by i18n WG yet).

**Comment by xfq** [comment]
Filed https://github.com/w3c/webrtc-svc/issues/32 per i18n teleconference.
