### ISSUE TITLE
Web Share API > 2020-06-05

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#114]
Note that the i18n WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://www.w3.org/International/review-request#selfreview.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Web Share API
- URL of spec: https://www.w3.org/TR/web-share/

- Do you need a reply by a particular date? 2020-Jun-05
- Any information arising from a self-review? N/A
- Where and how to file issues arising? https://github.com/w3c/web-share/issues/
- Pointer to any explainer for the spec? N/A

Other comments:

Hello,

The WebApps WG would welcome your review of the Web Share API FPWD [1].

If you have any comments or questions following your review, please could you file them as issues on the Web Share API Github repository [2].

If you're able to complete your review by Friday 5 June 2020 it would be appreciated. Thank you.

Léonie
[1]
https://www.w3.org/TR/web-share/
[2]
https://github.com/w3c/web-share/issues/

-- Director @TetraLogical

**Comment by xfq** [comment]
I have reviewed this document. This only issue I found was that the `text` and `title` members can't be associated with language and (base) direction metadata (or label language/direction changes inline).

We already have an issue for that: https://github.com/w3c/i18n-activity/issues/248

**Comment by himorin** [comment]
I did not find any additional point, neither.
Section 3.1 might be required to be rewritten following addition of lang/dir (e.g. some sharing method may have such capability), but it's non-normative.

**Comment by aphillips** [comment]
I pulled this back from "awaiting comment resolution" because in the course of addressing action-896 I noticed a new comment w3c/i18n-activity#901

**Comment by aphillips** [comment]
Replaced with new request: https://github.com/w3c/i18n-request/issues/129
