### ISSUE TITLE
CSS Color 4 > 2020-10-31

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#116]
We have conducted a self-review of our spec [CSS Color 4](https://drafts.csswg.org/css-color-4/), and the results can be found at https://github.com/w3c/csswg-drafts/issues/5034.

Please check our findings.

- Do you need a reply by a particular date? 

Not really. The specification is firming up, but is not yet complete and is unlikely to get to CR for 6 months or more.

Other comments:

Honestly think there is nothing for you to review here. This specification is about making colors. That is all. But a quick glance would still be appreciated!

**Comment by xfq** [comment]
I have reviewed the spec and didn't found any:

* natural language text that would be read/searched by a user
* issues regarding character encoding
* markup elements/attributes
* local date/time/format

The named colors and system colors are [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive), which look good to me.

We might need to add a note to the [Transparency](https://drafts.csswg.org/css-color-4/#transparency) section about the glyph overlap issue ([here's a test](https://w3c.github.io/i18n-tests/results/cursive#text_opacity)). We can discuss it in the next i18n teleconference.

**Comment by xfq** [comment]
Filed https://github.com/w3c/i18n-activity/issues/910 , pending discussion by i18n WG.

**Comment by r12a** [comment]
NOTE: Please don't comment on the thread pointed to by @xfq.  We will in due course send a comment your way.

**Comment by svgeesus** [comment]
Noting that this is now "Completed" and that the [overlapping text opacity issue](https://github.com/w3c/i18n-activity/issues/910) is now resolved and closed, should this issue still be open or can it be closed?

**Comment by aphillips** [comment]
@svgeesus This is in our radar as "completed". We review and close these periodically.
