### ISSUE TITLE
Geolocation API 2020-06-24 > 2020-07-31

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-request#122]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Geolocation API Specification
- URL of spec: https://w3c.github.io/geolocation-api/

- What and when is your next expected transition? Publish a new CR in a month or so (early August)
- Any information arising from a self-review? Not really. The spec does not contain any natural language text that would be read/searched by a user. Location information is represented by latitude and longitude coordinates.
- Where and how to file issues arising? https://github.com/w3c/geolocation-api/issues
- Pointer to any explainer for the spec? Not available.

Other comments:

The spec contains the following substantive changes since the last REC:

* [Now Controlled by feature policy](https://github.com/w3c/geolocation-api/pull/41)
* [Fixed confusion around callback interfaces not being an EventHandler](https://github.com/w3c/geolocation-api/pull/39)
* Only expose the API in SecureContexts
* [Renamed](https://github.com/w3c/geolocation-api/pull/23) the interfaces and dictionaries + removal of `[NoInterfaceObject]` + `[SameObject]` annotation on geolocation attribute

**Comment by himorin** [comment]
memo

- [html diff to previous REC](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FREC-geolocation-API-20161108%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fgeolocation-api%2F)
- The only natural language string is [GeolocationPositionError.message attribute](https://w3c.github.io/geolocation-api/#position_error_interface), which is provided in parallel to GeolocationPositionError.code, and noted as "This attribute is primarily intended for debugging and developers SHOULD NOT use it directly in their application user interface.". This attribute is not for display use, and should be fine to be kept as is.

In total, I see no issue on i18n point of view for this draft.

**Comment by himorin** [comment]
Added one issue as: https://github.com/w3c/geolocation-api/issues/50
