### ISSUE TITLE
MediaStreamTrack Content Hint 2020-07-28 > 2020-08-28

### ISSUE THREAD

**Issue by caribouW3** [w3c/i18n-request#125]
- name of spec to be reviewed: MediaStreamTrack Content Hints
- URL of spec: https://www.w3.org/TR/2020/WD-mst-content-hint-20200728/

- What and when is your next expected transition?  CR in september 2020.
- What has changed since any previous review? no previous review
- Any information arising from a self-review? The spec has a priori no I18N intersection (no human interaction)
- Where and how to file issues arising? https://github.com/w3c/mst-content-hint/issues
- Pointer to any explainer for the spec? https://github.com/w3c/mst-content-hint/blob/gh-pages/explainer.md

Other comments:

**Comment by himorin** [comment]
One DOMString attribute is defined (`MediaStreamTrack.contentHint`) in this spec, but is defined to take pre-defined enum like us-ascii string. No other natural language related feature nor attribute. No cultural etc. dependent value or behavior is used.

No issue found in this draft specification on i18n point of view.
