### ISSUE TITLE
Screen Wake Lock API 2020-08-06 > 2020-09-30

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-request#128]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Screen Wake Lock API
- URL of spec: https://w3c.github.io/screen-wake-lock/

- What and when is your next expected transition? Publish a new CR before October.
- Any information arising from a self-review? Not really. The spec does not contain any natural language text that would be read/searched by a user.
- Where and how to file issues arising? https://github.com/w3c/screen-wake-lock/issues
- Pointer to any explainer for the spec? Not available.

Other comments:

Changes since the last CR: https://w3c.github.io/screen-wake-lock/#changes-20171214

**Comment by himorin** [comment]
No natural language related feature nor attribute (incl. ones defined as DOMString). 
No cultural etc. dependent value or behavior is used.

No issue found in this draft specification on i18n point of view.
