### ISSUE TITLE
WebRTC Priority Control API 2020-09-24 > 2020-10-23

### ISSUE THREAD

**Issue by caribouW3** [w3c/i18n-request#131]
Hi, 

- name of spec to be reviewed: WebRTC Priority Control API
- URL of spec: https://www.w3.org/TR/2020/WD-webrtc-priority-20200922/

- What and when is your next expected transition?  CR in November 2020.
- What has changed since any previous review? no previous review
- Any information arising from a self-review? The spec has a priori no I18N intersection (no human interaction)
- Where and how to file issues arising? https://github.com/w3c/webrtc-priority/issues/
- Pointer to any explainer for the spec? https://github.com/w3c/webrtc-priority/blob/master/explainer.md

**Comment by r12a** [comment]
i18n WG folks: I had a look at this, and found nothing to report.

**Comment by aphillips** [comment]
The I18N WG performed a review of this spec and found no issues. I was [actioned](https://www.w3.org/International/track/actions/959) to notify WebRTC-priority of this in the 2020-10-01 teleconference.
