### ISSUE TITLE
CSS Conditional 2020-11-05 > 2020-11-28??

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#136]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: CSS Conditional
- URL of spec: https://drafts.csswg.org/css-conditional-3/

- What and when is your next expected transition? 
- What has changed since any previous review? 
- Any information arising from a self-review? 
- Where and how to file issues arising? 
- Pointer to any explainer for the spec? 

Other comments: Created from https://github.com/w3c/csswg-drafts/issues/5568

**Comment by r12a** [comment]
I reviewed this and found no i18n-specific comments.

**Comment by aphillips** [comment]
I18N has completed this review and found no new issues. Thank you for requesting a review from I18N.
