### ISSUE TITLE
CSS Color Adjustment Level 1 2020-11-09 > 2021-02-15

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#137]
- name of spec to be reviewed: _CSS Color Adjustment Level 1_
- URL of spec: https://www.w3.org/TR/css-color-adjust-1/

- What and when is your next expected transition? to CR, likely Q1 2021
- What has changed since any previous review? no formal previous review
- Any information arising from a self-review? none
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues
- Pointer to any explainer for the spec? none

Other comments:
This spec does not deal with user-input or text in any fashion. It is only about colors. I think it would be fine if i18n wants to waive review rather than spending time on it; but we wanted to make sure it's on your radar so that we can transition to CR with your sign-off when we're done.

**Comment by himorin** [comment]
I see no string related, cultural, nor internationalization aware property or value in the spec. 
In addition, I had slight concern on a item listed in properties:

- vendor prefixed CSS property (`-webkit-tap-highlight-color`) is mentioned in section 3.1, properties affected by force override

for other minor points (typo etc.) not related to i18n, already submitted individual issue/PR(s).
