### ISSUE TITLE
DOM Review Draft — Published 15 June 2020 2020-11-17 > 2020-12-29

### ISSUE THREAD

**Issue by siusin** [w3c/i18n-request#138]
- name of spec to be reviewed: DOM Review Draft — Published 15 June 2020
- URL of spec: https://dom.spec.whatwg.org/review-drafts/2020-06/

- What and when is your next expected transition? CR, January 2021
- What has changed since any previous review? 
   - changes: https://github.com/w3c/htmlwg/issues/14#issuecomment-728034670
   - please pay attention to: [Add StaticRange constructor](https://github.com/whatwg/dom/commit/a93f9f8be626740f6ac4a459bfb28322e27646d1)
- Any information arising from a self-review? none.
- Where and how to file issues arising? 
   - Issues identified during wide and horizontal review should be filed directly on the [WHATWG DOM repository](https://github.com/whatwg/dom/issues/), but please let the HTML WG have a pointer to the mechanism or place where you track your issues by email to public-html@w3.org.
- Pointer to any explainer for the spec? 
   - The WHATWG published a new Review Draft of the DOM Standard on 15 June 2020. The HTML
WG plans to take this Review Draft to W3C Recommendation in 2021, thus we are inviting another wide and horizontal review of [the commits of the DOM Standard between 19 June 2019 (b5eac4d) and 15 June 2020 (ad06a4c)](https://github.com/whatwg/dom/commits/master?before=ad06a4c686a62a2a0f175125932200930364c170+35).

Other comments: thank you!

**Comment by xfq** [comment]
I didn't find any i18n issue.

The DOM specification does not deal with typographic features, local date/time/format, or content negotiation. Language and text direction metadata are handled by HTML.

Note that we have an open issue for DOM: https://github.com/w3c/i18n-activity/issues?q=is%3Aopen+is%3Aissue+label%3As%3Adom

**Comment by xfq** [comment]
BTW, there were some discussions about DOM Ranges in TPAC 2020: https://www.w3.org/2020/10/22-i18n-minutes.html#item03

IIUC each range have two boundary points, and a boundary point is a tuple consisting of a node and an offset. For Text nodes, the offset is code unit (rather than grapheme cluster) based. If I understand correctly, surrogate pairs can be split.

**Comment by siusin** [comment]
Thank you! Shall we close this issue?

**Comment by xfq** [comment]
It's just my review and it has not been discussed at the i18n teleconference yet. We will let you if the i18n WG is OK with the DOM spec later. Thank you!

**Comment by aphillips** [comment]
[I18N-ACTION-983] The I18N WG reviewed DOM in [today's teleconference](https://www.w3.org/2020/12/10-i18n-minutes.html). We have posted one new issue to WHATWG. We do not have any issues that will block publication of the snapshot.

**Comment by siusin** [comment]
Thank you I18N!
