### ISSUE TITLE
Audio Output Devices API 2020-11-27 > 2020-mm-dd

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#144]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Audio Output Devices API
- URL of spec: https://www.w3.org/TR/2020/CRD-audio-output-20201127/

- What and when is your next expected transition? 
- What has changed since any previous review? 
- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist)
- Where and how to file issues arising? 
- Pointer to any explainer for the spec? 

Other comments:

Wide review request taking from public-review-announce@

Abstract

This document defines a set of JavaScript APIs that let a Web application manage how audio is rendered on the user audio output devices.

Status of the Document

This section describes the status of this document at the time of its publication. Other documents may supersede this document. A list of current W3C publications and the latest revision of this technical report can be found in the W3C technical reports index at https://www.w3.org/TR/.

The WebRTC and Device and Sensors Working Group intend to publish this specification as a Candidate Recommendation soon. Consequently, this is a Request for wide review of this document.

This document was published by the Web Real-Time Communications Working Group as a Candidate Recommendation Draft. This document is intended to become a W3C Recommendation.

GitHub Issues are preferred for discussion of this specification. Alternatively, you can send comments to our mailing list. Please send them to public-webrtc@w3.org (archives).

Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Draft integrates changes from the previous Candidate Recommendation that the Working Group intends to include in a subsequent Candidate Recommendation Snapshot.

This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

**Comment by himorin** [comment]
This spec uses two DOMString attributes, which are supposed to be language neutral label, as:

- `sinkId` in `HTMLMediaElement`, which is defined as a copy from `MediaDeviceInfo.deviceId` ([best practice](https://www.w3.org/TR/mediacapture-streams/#generating-deviceids) for generation of deviceId recommends to use a cryptographic hash, in mediacapture-streams spec, no natural string)
- `deviceId` in `AudioOutputOptions` dictionaly for `MediaDevices.selectAudioOutput`, which takes one or some of `sinkId` (above)

no other cultural oriented value nor mechanism is used.

I see no issue on i18n point of view for this draft.
