### ISSUE TITLE
CSS Text Level 3 2020-12-01 > 2020-12-??

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#146]
- name of spec to be reviewed: CSS Text Level 3
- URL of spec: https://www.w3.org/TR/css-text-3/

- What and when is your next expected transition? To CR, as soon as HR groups sign off
- What has changed since any previous review? https://www.w3.org/TR/css-text-3/#changes see particularly https://www.w3.org/TR/css-text-3/#bidi-linebox
- Please point to the results of your own self-review
- Where and how to file issues arising?  in CSSWG github
- Pointer to any explainer for the spec? none

Other comments:

This spec is a close collaboration between CSSWG and i18n. We've edited in the last few substantial issues and republished. (There are a couple [minor issues](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-text-3) still to resolve, but they shouldn't affect i18n review.)  Would like to ask i18n to sign off before we request a transition to CR.

We will of course continue processing comments after CR as well, but the spec is quite stable overall and it would be great to put it in CR at last.

**Comment by aphillips** [comment]
@fantasai thanks for the HR request. Can you give me a little more info on your actual dates? Given the holidays at the end of the year, we likely have only a couple of teleconferences left before 2021. Since this isn't exactly a New Thing, this may not be a problem, but I'd hate to miss any important deadlines for CSS. When are you looking to go CR? If needed, can you wait for early January?

**Comment by r12a** [comment]
I took a look at these changes.  I raised a couple of minor questions:

https://github.com/w3c/csswg-drafts/issues/5758
https://github.com/w3c/csswg-drafts/issues/5759

but otherwise the changes seem ok to me.

**Comment by fantasai** [comment]
@aphillips Well, I'd love to get this transitioned before the end of the year. But if necessary we can wait until January.

**Comment by aphillips** [comment]
@fantasai We'll do our best. I'll update you after our telecon tomorrow (Thursday, 3 Dec) so you can adjust expectations.

**Comment by aphillips** [comment]
In [today's teleconference](https://www.w3.org/2020/12/10-i18n-minutes.html), I18N completed the review of CSS3-Text module. There are no remaining blocking issues that we are aware of. There are still some tracking issues open, but we do not believe that any are currently in the way of a CR transition. We look forward to seeing your CR and continuing to work with CSS on v4 of Text.

**Comment by aphillips** [comment]
(Forgot to say: this is I18N-ACTION-984)
