### ISSUE TITLE
Notice of FPWD: CSS Custom Highlight API Module Level 1 2020-12-08

### ISSUE THREAD

**Issue by frivoal** [w3c/i18n-request#147]
Hi i18n, this is more of a heads up than a strict request for review.

The CSSWG's Custom Highlight API Module Level 1 was recently published as a FPWD, and as one of its editors, I thought this was a good time to let you know of its existence and invite initial review.

I have completed the self-review, and found no particular concern with this specification, but it seemed neighborly to let you know of it nonetheless.

> name of spec to be reviewed:

CSS Custom Highlight API Module Level 1

> URL of spec:

https://www.w3.org/TR/css-highlight-api-1/

> Do you need a reply by a particular date?

Not in particular, this is just a heads up in case you want to have a look, this is still early.

> Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist) 

https://github.com/w3c/csswg-drafts/issues/5771

> Where and how to file issues arising? 

Please raise any issues in the csswg GitHub repo: https://github.com/w3c/csswg-drafts/issues

> Pointer to any explainer for the spec? 

A standalone explainer exists at https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/highlight/explainer.md It is no longer maintained, and is effectively superseded by the introduction section of the specification, but may be of interest for discussion of possible alternatives.

> Other comments:

If you think this specification has nothing of interest for your group, please let us know. Otherwise, we will request review again when we get close to CR, and if anything major changes before then.

**Comment by xfq** [comment]
I have reviewed this document and found no i18n issues. I'll file an issue against DOM about potential issues caused by fragment boundaries in the middle of grapheme clusters in the `Range` object.

**Comment by xfq** [comment]
DOM issue: https://github.com/whatwg/dom/issues/933

**Comment by aphillips** [comment]
All issues are closed.
