### ISSUE TITLE
ARIA in HTML > 2021-04-02

### ISSUE THREAD

**Issue by LJWatson** [w3c/i18n-request#150]
We're preparing to transition [ARIA in HTML](https://www.w3.org/TR/2021/WD-html-aria-20210301/
) to CR and we'd welcome your review.

You last reviewed ARIA in HTML [in 2018](https://github.com/w3c/i18n-activity/issues/322). There have been changes to the spec [since then](https://github.com/w3c/html-aria/issues?q=is%3Apull+closed%3A%3E2018-11-01
).
If it's possible for you to complete your review by 2 April, we'd be grateful. The WebApps WG will be rechartering in April/May and we'd very much like to request transition to CR before then if we can.

Please file your comments and issues on the [ARIA in HTML repo](https://github.com/w3c/html-aria/issues
), using the appropriate [horizontal review labels](https://github.com/w3c/html-aria/labels).

If you could reply here to let us know when your review is complete, that would be helpful.

With thanks

**Comment by aphillips** [comment]
@LJWatson The I18N WG has completed a review and no substantive issues were found. Thank you and good luck with your upcoming CR transition. (you'll also receive an email about this)
