### ISSUE TITLE
CSS Multi-column Layout Module Level 1 2021-05-09 > 2021-06-01

### ISSUE THREAD

**Issue by rachelandrew** [w3c/i18n-request#153]
- name of spec to be reviewed: _CSS Multi-column Layout Module Level 1_
- URL of spec: https://www.w3.org/TR/css-multicol-1/
- What and when is your next expected transition? To CR once I have HR signoff.
- What has changed since any previous review? No previous review that I am aware of
- Please point to the results of your own self-review: no issues from self-review
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues
- Pointer to any explainer for the spec? none

Other comments: This specification was in CR, and was moved back to WD status after a long period of no updates. It is well implemented already in browsers and print user agents.

**Comment by xfq** [comment]
I have reviewed this document and found no i18n issues.

This feature can be adapted according to the writing mode, which looks good to me, and it does not deal with natural language text or local date/time/format.

**Comment by r12a** [comment]
The only mention of vertical text appears to be:

> To ensure that column-width can be used with vertical text, column width means the length of the line boxes inside the columns.

I think it would be good to make this more visible, and to include examples of vertical text in Japanese and Mongolian so that implementers are clear that they run horizontally (and in different directions) in those writing systems.

**Comment by r12a** [comment]
@rachelandrew note that that's intended to be an internal comment.  If the i18n WG decides to support this idea, we'll raise a separate issue in your GH repo.
