### ISSUE TITLE
CSS Counter Styles L3 2021-06-07 > 2021-06-30?

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#157]
- name of spec to be reviewed: CSS Counter Styles L3
- URL of spec: https://drafts.csswg.org/css-counter-styles-3/#changes-2017

- Current Rec/Note phase? CR
- What and when is your next expected transition? once i18n and a11y sign off
- What has changed since any previous review? https://drafts.csswg.org/css-counter-styles-3/issues-cr-2017
- Please point to the results of your [self-review](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) N/A
- Where and how to file issues arising?  https://github.com/w3c/csswg-drafts/issues
- Pointer to any explainer for the spec? 

Other comments:

Updating the spec, just want to make sure i18n is OK with the changes and disposition of comments before we submit to the Director, since this is a joint effort.
Changes list at https://drafts.csswg.org/css-counter-styles-3/#changes-2017
DoC at https://drafts.csswg.org/css-counter-styles-3/issues-cr-2017 (13 issues total)

**Comment by r12a** [comment]
I took a look at all these changes today and didn't see anything that was a concern for i18n review.

**Comment by r12a** [comment]
There is, however, an editorial glitch: https://drafts.csswg.org/css-counter-styles-3/#additional-predefined has the wrong title.

**Comment by fantasai** [comment]
@r12a Ah, right. You did mention that. :) Fixed.

**Comment by fantasai** [comment]
Thanks for the quick review!

**Comment by xfq** [comment]
I took a look and found no problems either.
