### ISSUE TITLE
DOM Review Draft — Published 21 June 2021 > 2021-08-31

### ISSUE THREAD

**Issue by siusin** [w3c/i18n-request#160]
- name of spec to be reviewed: DOM Review Draft — Published 21 June 2021
- URL of spec: https://dom.spec.whatwg.org/review-drafts/2021-06/

- What and when is your next expected transition? 2021-08-31, CR
- What has changed since any previous review? Please look at the [list of important changes](https://github.com/w3c/htmlwg/issues/19).
- Where and how to file issues arising? Please file an issue via https://github.com/whatwg/dom/issues.

Other comments:
Thank you!

**Comment by xfq** [comment]
I didn't find any i18n issue.

The DOM specification does not deal with typographic features, local date/time/format, or content negotiation. Language and text direction metadata are handled by HTML.

Currently, we have two open issues against DOM: https://github.com/w3c/i18n-activity/issues?q=is%3Aopen+is%3Aissue+label%3As%3Adom

I will discuss with the i18n WG and let you know if the i18n WG is OK with this DOM Review Draft. Thank you!

**Comment by aphillips** [comment]
We discussed this in the teleconference of 2021-07-29 and agreed that our review was complete.
