### ISSUE TITLE
CSS Masking Module Level 1 2021-08-05 > 2021-11-05

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#162]
- name of spec to be reviewed: **CSS Masking Module Level 1**
- URL of spec: https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/

- What and when is your next expected transition? CR Snapshot, after wide review is complete
- What has changed since any previous review? [changes since 2014 CR](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#changes)
- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist) [here](https://github.com/w3c/fxtf-drafts/issues/433)
- Where and how to file issues arising? Please file an issue on [fxtf repo](https://github.com/w3c/fxtf-drafts/issues)
- Pointer to any explainer for the spec? Please see [the Introduction](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#intro)

Other comments:

**Comment by xfq** [comment]
I took a look at this spec and didn't see anything that was a concern for i18n review.

**Comment by svgeesus** [comment]
Thanks @xfq I tend to agree, this spec is purely about graphical operations, but it needs to be reviewed anyway

**Comment by xfq** [comment]
We discussed this in the i18n WG teleconference of 2021-08-19 and agreed that our review was complete.
