### ISSUE TITLE
CSS Scrollbars 2021-08-29 > 2021-09-30

### ISSUE THREAD

**Issue by frivoal** [w3c/i18n-request#163]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: CSS Scrollbars Level 1
- URL of spec: https://www.w3.org/TR/css-scrollbars-1/

- What and when is your next expected transition?
    We're planing to go to CR soon, for a loosely defined value of soon. As soon as HR completes, unless something unexpected shows up.
- What has changed since any previous review?
     I am unsure that there was a previous review for i18n
- Please point to the results of your own self-review: https://github.com/w3c/csswg-drafts/issues/6554
- Where and how to file issues arising?  https://github.com/w3c/csswg-drafts/labels/css-scrollbars-1
- Pointer to any explainer for the spec? https://github.com/felipeerias/css-scrollbars-explainer

Other comments:
We expect this spec to be uninteresting from an i18n point of view.

**Comment by r12a** [comment]
I took a look at this spec, and saw no i18n-related issues.  Over to the other members of the i18n WG for further review.

**Comment by aphillips** [comment]
The I18N WG completed a review of this spec and found no issues. Thank you.
