### ISSUE TITLE
css-display-3 2021-09-03 > 2021-10-??

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#164]
- name of spec to be reviewed: CSS Display Module Level 3
- URL of spec: https://www.w3.org/TR/css-display-3/

- What and when is your next expected transition? 
    - CR Snapshot as soon as HR completes
- What has changed since any previous review? 
    - Copied over `order` property definition from Flexbox.
    - Copied over `visibility` property definition from CSS2 and expanded it to explain interactivity and a11y implications.
    - See full Changes list at https://www.w3.org/TR/css-display-3/#changes
    - See Disposition of Comments at https://drafts.csswg.org/css-display-3/issues-cr-2020
- Please point to the results of your own self-review
    - Nothing applicable.
- Where and how to file issues arising? 
    - Issues in the [CSSWG repo](https://github.com/w3c/csswg-drafts/issues) with `[css-display]` in the title.
- Pointer to any explainer for the spec? 
    - N/A

Other comments:

I don't think there is anything relevant for i18n to review here. Filing request for completeness, feel free to waive.

**Comment by r12a** [comment]
I took a look at this, and could see no i18n-related issues.

**Comment by aphillips** [comment]
I18N completed a review and found no issues.
