### ISSUE TITLE
Secure Payment Confirmation 2021-08-31 > 2021-10-08

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/i18n-request#165]
Note that the i18n WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://www.w3.org/International/review-request#selfreview.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Secure Payment Confirmation
- URL of spec: https://w3c.github.io/secure-payment-confirmation/

- Do you need a reply by a particular date? No. 

- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist) 

* SPC implementations render a modal window that displays human readable information provided by a Relying Party. 
* There is also text provided by the browser itself, presumably in the browser language selected by the user.

- Where and how to file issues arising? 

https://github.com/w3c/secure-payment-confirmation/issues

- Pointer to any explainer for the spec? 

https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md

Other comments:

* I anticipate requesting a joint meeting with the I18N WG during TPAC 2021.

**Comment by aphillips** [comment]
@ianbjacobs Could your WG please complete a self-review?

**Comment by ianbjacobs** [comment]
Hi @aphillips,

Started the review here:
https://github.com/w3c/secure-payment-confirmation/issues/93
