### ISSUE TITLE
Incremental Font Transfer 2021-10-09 > 2021-11-19

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#166]
We have conducted a self-review of our spec [Incremental Font Transfer](https://w3c.github.io/IFT/Overview.html), and the results can be found at https://github.com/w3c/IFT/issues/36.

Please check our findings.

- Do you need a reply by a particular date? 
No rush, we only recently went to FPWD

Other comments:
This specification allow a Web font to be transferred incrementally, on an as-needed basis, rather than all at once. Actually using the font is no different to regular fonts in CSS.

**Comment by aphillips** [comment]
Fixed submission date; added target due date. Note that 19 November is arbitrary.

**Comment by aphillips** [comment]
close in teleconference 2022-06-23

**Comment by svgeesus** [comment]
FYI an [updated WD of IFT has been published](https://www.w3.org/TR/2022/WD-IFT-20220628/) which puts into one specification the Range Request and Patch-subset methods, and describes how client and server negotiate which method to use. Feel free to review this new draft if you would like, in particular the material on Range Request.

**Comment by svgeesus** [comment]
A [new WD of IFT](https://www.w3.org/TR/2024/WD-IFT-20240709/) is available. This addresses review feedback from the earlier proposals. There is no longer a Range Request vs Patch Subset choice, and there is no longer any special protocol required. Compared to the earlier proposals, the risks of fingerprinting have been reduced and there should no longer be an impact on CDN caching.

In terms of I18n capabilities there is no functional gain or loss compared to earlier proposals. Just that the current proposal is more likely to be widely implemented, which will be of particular benefit for scripts involving large character repertoires. Of course, further review from an I18n perspective is warmly invited.

Because this is a substantial rewrite, we have [an Explainer](https://github.com/w3c/IFT/blob/main/IFT-Explainer.md)

**Comment by aphillips** [comment]
@svgeesus Will you be requesting a new review from us?

**Comment by svgeesus** [comment]
Yes, I will request a new review.

 - https://github.com/w3c/i18n-request/issues/238
