### ISSUE TITLE
CSS Conditional 4 2022-01-14 > 2022-03-14

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#168]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: **CSS Conditional Rules Module Level 4**
- URL of spec: [https://www.w3.org/TR/css-conditional-4/](https://www.w3.org/TR/css-conditional-4/)

- What and when is your next expected transition?
  - Candidate Recommendation
- What has changed since any previous review?
  - Since the [previous horizontal review of CSS Conditional 3](https://github.com/w3c/csswg-drafts/issues/5569) one new feature has been added, as described below.
- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist)
  - Nothing in the checklist seems applicable to this very short specification.
- Where and how to file issues arising?
  - As an [issue in our GitHub, please](https://github.com/w3c/csswg-drafts/labels/css-conditional-4)
- Pointer to any explainer for the spec?
  - [Explainer for `selector()` in `@supports`](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) by L. David Baron

Other comments:

This is currently a delta specification to [CSS Conditional 3](); the plan is to copy in all of that spec into this one, but currently this very short spec just has the one new feature relative to Level 3.

CSS Conditional 3 already has the ability to test whether CSS properties and property values are supported, before using them. This specification adds the ability to test of Selectors as well. From an I18n standpoint, this new feature merely combines two existing widely-implemented specifications which have already undergone review (Selectors, and the `@supports` functionality from CSS Conditional 3)

This specification, currently a Working Draft, is being advanced to CR soon because [all modern browsers now support it](https://caniuse.com/mdn-css_at-rules_supports_selector)

The published /TR specification does not have an example. Sorry! The [explainer](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) does, and one was also [just added to the ED](https://drafts.csswg.org/css-conditional-4/) plus test suite coverage. Apart from that, the /TR and ED are identical.

**Comment by himorin** [comment]
(memo)

This spec specifies only at-rule and its conditional syntax, but not condition itself which are defined in media queries, such as `display: flex` for support.
Found no issue related to i18n, nor no natural language or cultural information handling.

**Comment by himorin** [comment]
I18N completed a review and found no issues.

https://www.w3.org/2022/01/27-i18n-minutes.html#x078
