### ISSUE TITLE
Incremental Font Transfer via Range Request 2022-01-25 > 2022-03-30?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#170]
Note that the i18n WG prefers groups to run a self-review around the time of FPWD. Let us know when you have done it. Get advice on how to do that at https://www.w3.org/International/review-request#selfreview.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Incremental Font Transfer via Range Request
- URL of spec: https://w3c.github.io/IFT/RangeRequest.html

- Do you need a reply by a particular date? (Unknown)
- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist) 
- Where and how to file issues arising? https://github.com/w3c/IFT/issues/new
- Pointer to any explainer for the spec? (Unknown)

Other comments: [I18N-ACTION-1111]

**Comment by himorin** [comment]
didn't find any i18n related issue with this spec. 
talking with Japanese font vendors on parameters and/or optimization vectors.

**Comment by xfq** [comment]
This spec was merged into the main IFT spec (see https://github.com/w3c/IFT/pull/76).

Should we merge the review requests (https://github.com/w3c/i18n-request/issues/170 and https://github.com/w3c/i18n-request/issues/166)?

**Comment by xfq** [comment]
Ah, I just found that this is in the Completed column. Closing.
