### ISSUE TITLE
Urlpattern 2022-02-28 > 2022-03-31?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#173]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: URLPattern API
- URL of spec: https://wicg.github.io/urlpattern/

- Current Rec/Note phase? Draft Community Report
- What and when is your next expected transition? Unknown
- What has changed since any previous review?  N/A
- Please point to the results of your [self-review](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) 
- Where and how to file issues arising? https://github.com/WICG/urlpattern
- Pointer to any explainer for the spec? https://github.com/WICG/urlpattern/blob/main/explainer.md

Other comments:

This is self-filed by I18N in response to [action item 1121](https://www.w3.org/International/track/actions/1122)

**Comment by xfq** [comment]
I have reviewed this document and found no i18n issues.
