### ISSUE TITLE
Baggage 2022-04-26 > 2022-05-27

### ISSUE THREAD

**Issue by kalyanaj** [w3c/i18n-request#176]
- name of spec to be reviewed:  W3C Baggage
- URL of spec: https://www.w3.org/TR/baggage/

- Do you need a reply by a particular date?  Yes, we are planning to get to CR in the coming few months.
- Please point to the results of your own self-review (see https://w3c.github.io/apa/fast/checklist.html): https://github.com/w3c/baggage/issues/93.
- Where and how to file issues arising?  https://github.com/w3c/baggage
- Pointer to any explainer for the spec?  https://github.com/w3c/baggage/blob/main/baggage/README.md provides an overview and the use cases. 

Other comments:

**Comment by himorin** [comment]
found no other point than already raised to i18n-activity
