### ISSUE TITLE
Web of Things (WoT) Architecture 1.1 2022-04-03 > 2022-06-30

### ISSUE THREAD

**Issue by mmccool** [w3c/i18n-request#178]
Ready for review.  The WD will be updated shortly based on branch [architecture-1.1-pre-cr-wd](https://github.com/w3c/wot-architecture/tree/architecture-1.1-pre-cr-wd)

- Name of spec to be reviewed:
    - Web of Things (WoT) Architecture 1.1
- URL of spec:
    * Editor's: https://w3c.github.io/wot-architecture/
    * Last published: https://www.w3.org/TR/wot-architecture11/
    * Branch for review (WD to be updated shortly): https://github.com/w3c/wot-architecture/tree/architecture-1.1-pre-cr-wd
- What and when is your next expected transition?
    * The CR transition is planned for 30 June 2022
- What has changed since any previous review?
    * See change log; updates to cover new deliverables, including Discovery
- Please point to the results of your own self-review:
    * https://github.com/w3c/wot-architecture/blob/main/publication/ver11/internationalization.md
- Where and how to file issues arising?
    * As an [issue in our GitHub](https://github.com/w3c/wot-architecture/issues), please 
- Pointer to any explainer for the spec?
    * https://github.com/w3c/wot-architecture/blob/main/explainer/explainer11.md

Other comments:

**Comment by xfq** [comment]
All issues are closed.
