### ISSUE TITLE
CSS Color 5 2022-05-30 > 2022-08-30

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#183]
- name of spec to be reviewed: **CSS Color Module Level 5**
- URL of spec: https://drafts.csswg.org/css-color-5/ or https://www.w3.org/TR/2022/WD-css-color-5-20220428/

- What and when is your next expected transition? CR, but not for a few months
- What has changed since any previous review? No previous review
- Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist) Nothing on the checklist seems applicable to this specification
- Where and how to file issues arising? On the [CSS WG GitHub repo](https://github.com/w3c/csswg-drafts/issues/), please.
- Pointer to any explainer for the spec? https://drafts.csswg.org/css-color-5/#intro

Other comments:

This specification deals with color calculations such as mixing colors, modifying colors, and calculating color contrast. As far as we can tell, there is no I18n component but of course we wanted to check.

The specification is now being implemented in Safari and in Firefox, and may move to CR in a few months.

Our [CSS Color 5 horizontal review issue](https://github.com/w3c/csswg-drafts/issues/7297)

**Comment by himorin** [comment]
no natural language text in this spec. Also I've not found any cultural related text/words in description.
propose to move this to review completed without any issue raised.

**Comment by r12a** [comment]
i also scrolled through this spec, and found nothing to comment on from an i18n perspective

**Comment by himorin** [comment]
memo: no issue found, and resolved to mark as review completed
https://www.w3.org/2022/06/09-i18n-minutes.html#t04
