### ISSUE TITLE
Autoplay Policy Detection API 2022-09-01 > 2022-09-30

### ISSUE THREAD

**Issue by alastor0325** [w3c/i18n-request#192]
### Name of your specification

Autoplay Policy Detection API

### URL of your specification

https://w3c.github.io/autoplay/

### URL for your results

https://github.com/w3c/autoplay/issues/31

### Other comments

We have finished our self-review check lists, thank you!

**Comment by alastor0325** [comment]
Filed https://github.com/w3c/i18n-request/issues/192 in [i18n-request](https://github.com/w3c/i18n-request).

**Comment by aphillips** [comment]
@alastor0325 Thanks for this request. I have arbitrarily assigned a completion date of 2022-09-30. Please let me know if you need it sooner (noting that TPAC will impact our schedule somewhat).

**Comment by xfq** [comment]
I took a look at this, and could see no i18n-related issues.

**Comment by aphillips** [comment]
I18N completed a review of this document and found no issues. Good luck with your CR. (Reviewed in telecon of 2022-09-15)
