### ISSUE TITLE
Trace Context 2022-09-22 > 2022-11-03

### ISSUE THREAD

**Issue by kalyanaj** [w3c/i18n-request#193]
### Name of your specification

Trace Context Level 2

### URL of your specification

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Ftrace-context-1%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2022%2FWD-trace-context-2-20220929%2F

### Do you need a reply by a particular date?

We are looking to get to CR status before end of year

### Please point to the results of your own self-review

https://github.com/w3c/trace-context/issues/498

### Where and how should the i18n WG raise issues?

https://github.com/w3c/trace-context/issues

### Pointer to any explainer for the spec

https://github.com/w3c/distributed-tracing-wg/blob/main/EXPLAINER.md

### Other comments

**What**: The main difference from Trace Context Level 1 (which is already in recommendation status) is the ability to express whether at least a part of the traceID has been randomly (or pseudo-randomly) generated.
**Why**: This enables downstream systems to use the trace ID for sampling purposes or for sharding purposes.
**How**: This is achieved by the introduction of a new flag called "Random Trace ID flag". If the newly introduced random-trace-id flag is set, at least the right-most 7 bytes of the trace-id MUST be randomly (or pseudo-randomly) generated.

**Comment by kalyanaj** [comment]
Thanks @aphillips for the review for Trace Context Level 2. 

The three issues filed from this review (https://github.com/w3c/trace-context/issues?q=label%3Ai18n-needs-resolution+) have been addressed/closed/backported to our Level 2 branch. Wanted to check if we can go ahead close this issue. Thanks!

https://github.com/w3c/trace-context/issues/506
https://github.com/w3c/trace-context/issues/507
https://github.com/w3c/trace-context/issues/508

**Comment by aphillips** [comment]
@kalyanaj Thanks for the pointer. We will close the books on this review. Thanks.
