### ISSUE TITLE
CSS Values and Units Level 4    2022-10-19 > 2023-3-20

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#194]
### Name of your specification

CSS Values and Units Level 4

### URL of your specification

https://www.w3.org/TR/css-values-4/

### When does the review need to be finished?

next 3-6 months is fine

### What has changed since any previous review?

Previous review was probably CSS Values and Units Level 3, so
  https://www.w3.org/TR/css-values-4/#additions-L3

### Please point to the results of your own self-review

None apply

### Where and how should the i18n WG raise issues?

https://github.com/w3c/csswg-drafts/issues

### Other comments

Particular interest to the i18nWG would be the length units, particularly the font-relative units
  https://www.w3.org/TR/css-values-4/#lengths

Note the open issue here, which is likely to result in a change:
  https://github.com/w3c/csswg-drafts/issues/7577

We don't anticipate any i18n concerns on any of the other new features.

**Comment by himorin** [comment]
I see no i18n related issue, no cultural value defined, all string comparisons are well defined by case insensitive or INFRA/is.
(Although I've added one non-i18n question as https://github.com/w3c/csswg-drafts/issues/8034 )

**Comment by himorin** [comment]
@fantasai no needs-resolution issue found for this spec. Thank you for contacting us for i18n horizontal review!
closing this as completed.
