### ISSUE TITLE
View Transitions    2022-10-28 > 2022-12-31*

### ISSUE THREAD

**Issue by khushalsagar** [w3c/i18n-request#196]
### Name of your specification

css-view-transitions-1

### URL of your specification

https://www.w3.org/TR/css-view-transitions-1/

### Please point to the results of your own self-review

https://github.com/WICG/view-transitions/issues/196

### Where and how should the i18n WG raise issues?

https://github.com/w3c/csswg-drafts/issues with [css-view-transitions-1] and css-view-transitions label.

### Pointer to any explainer for the spec

https://github.com/WICG/view-transitions/blob/main/explainer.md

**Comment by khushalsagar** [comment]
Friendly ping, we have responded to the issue raised on this review [here](https://github.com/w3c/csswg-drafts/issues/8230). Would appreciate another review to move this forward.

**Comment by aphillips** [comment]
@khushalsagar Do you wish a new review? If so, you should create a new issue in this repo using the template. We are currently reviewing w3c/csswg-drafts#8230, which is the issue we have open against this spec.

**Comment by khushalsagar** [comment]
@aphillips sorry for the confusion. I meant could you please take a look at the response on https://github.com/w3c/csswg-drafts/issues/8230. Does that resolve the concern raised?

**Comment by khushalsagar** [comment]
Please note, the latest published draft for this spec is [here](https://www.w3.org/TR/css-view-transitions-1/). This incorporates all open issues against this spec and we're working on pushing this to CR.

The changes in the latest draft since this review was opened are summarized [here](https://www.w3.org/TR/css-view-transitions-1/#changes). I don't think any of them affect i18n but would appreciate if you can validate that. If any particular change looks suspect, please feel free to ask and I'll try my best to give a succinct summary.

**Comment by khushalsagar** [comment]
@bert-github @aphillips  can this review be closed? https://github.com/w3c/csswg-drafts/issues/8230 has now been resolved.

**Comment by aphillips** [comment]
@khushalsagar Thanks for the ping. I18N reviewed this on our review radar on 2023-07-27 and closed this review.
