### ISSUE TITLE
Scroll-linked Animations Level 1    2022-11-18

### ISSUE THREAD

**Issue by fantasai** [w3c/i18n-request#197]
### Name of your specification

Scroll-linked Animations Level 1

### URL of your specification

https://www.w3.org/TR/scroll-animations-1/

### Do you need a reply by a particular date?

nope, take your time :)

### Please point to the results of your own self-review

None apply

### Where and how should the i18n WG raise issues?

https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Ascroll-animations-1

### Other comments

The draft already allows the relevant scroll axes to be defined in both logical and physical terms (`block | inline | horizontal | vertical`), and defaults to `block`, so I think that takes care of the main i18n concern with this technology.

Filing this request mainly as a formalism; I'm not convinced i18n needs to spend much time here other than be aware of it.

**Comment by aphillips** [comment]
Assigned due date of 2023-01-30 arbitrarily pending examination by I18N

**Comment by himorin** [comment]
memo for WG call: as mentioned in other comments, the only writing-mode related attribute is axis and has both logical and physical. see no other i18n related items.
proposing to review completed without any issue.

**Comment by himorin** [comment]
no i18n issue opened to the csswg-drafts repository, and closing this review request as completed.
