### ISSUE TITLE
Secure Payment Confirmation to CR (2 changes since last review)  2023-01-11 > 2023-02-09

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/i18n-request#201]
### Name of your specification

Secure Payment Confirmation

### URL of your specification

https://w3c.github.io/secure-payment-confirmation/

### When does the review need to be finished?

2023-02-01

### What has changed since any previous review?

In August 2022 the Web Payments Working Group requested pre-Candidate Recommendation horizontal review of Secure Payment Confirmation (SPC). All reviews led to satisfactory outcomes. Thank you for the I18N review:
 https://github.com/w3c/i18n-request/issues/190

Since then, the Web Payments Working Group has made or plans to make two non-editorial changes to the specification for which we seek additional horizontal review:

* The addition of an opt-out feature, requested by developers to help satisfy GDPR requirements. For background, see [issue 172](https://github.com/w3c/secure-payment-confirmation/issues/172) and the resulting [changes to the
  specification](https://github.com/w3c/secure-payment-confirmation/pull/215). Experimentation with this feature has demonstrated its utility to at least one organization that has experimented with SPC.
* The expected removal of a requirement that the user agent consume a user activation during authentication. For background, see [issue 216](https://github.com/w3c/secure-payment-confirmation/issues/216), including the Chrome Team's security and privacy consideration notes. Although we have not yet updated the specification to remove the user activation requirement, we seek your review at this time. We would anticipate the actual change to the specification to be small (and it would include the security and privacy considerations).

### Please point to the results of your own self-review

https://github.com/w3c/secure-payment-confirmation/issues/202

### Where and how should the i18n WG raise issues?

https://github.com/w3c/secure-payment-confirmation/issues/

### Pointer to any explainer for the spec

https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md

### Other comments

Here are some observations about how these changes relate to previously raised issues; see
  https://github.com/w3c/secure-payment-confirmation/issues?q=is%3Aclosed+label%3Ai18n-needs-resolution

1) Opt-out in the UX. Previous issue on locale hint is relevant:
    https://github.com/w3c/secure-payment-confirmation/pull/212

    Presumably the browser would use the same locale hint for the text informing
    the user about the ability to opt out.

2) There are no new input fields to the API that result in displayable strings. Thus,
     this issue is not relevant:
     https://github.com/w3c/secure-payment-confirmation/issues/208

3) There is no new example text. Thus this issue is not relevant:
    https://github.com/w3c/secure-payment-confirmation/issues/206

Note that the previous issue on lang/dir metadata has been left open for ongoing TC39 discussions, without objections to the WPWG advancing SPC to CR:
  https://github.com/w3c/secure-payment-confirmation/issues/205#issuecomment-1255167247

Thank you!

**Comment by aphillips** [comment]
Thanks @ianbjacobs for this request. Can you clarify your deadline? 1 February is a Wednesday and I18N meets on Thursdays. This only gives us a couple of weeks to perform the review and discuss any issues with you. If your date is semi-arbitrary, this may not matter. And, of course, we hope not to find any new issues :-). If you expect to submit a transreq on 1 Feburary, I'll try to expedite our review to the extent possible.

**Comment by ianbjacobs** [comment]
Hi @aphillips,

Thanks for the quick reply. We have flexibility on the date. Would 9 February work for you? (Assuming you meet that day.)

**Comment by aphillips** [comment]
@ianbjacobs Thanks! That's super helpful. We'll work to finish up by the 2nd (before if possible).

**Comment by aphillips** [comment]
@ianbjacobs I just filed the two issues we found, one of which is editorial. The other is thorny only from the point of view that you need to progress your spec and I still don't have a good answer for language and direction metadata for `displayName`. If necessary, let's chat about what (if anything) your spec needs to say about this.

**Comment by ianbjacobs** [comment]
Thanks, @aphillips. See:

1) Pull request to add locale to an example (editorial)
    https://github.com/w3c/secure-payment-confirmation/pull/229

2) Questions about a suggested Note:
     https://github.com/w3c/secure-payment-confirmation/issues/205#issuecomment-1408777086

**Comment by ianbjacobs** [comment]
Hi @aphillips,
I believe we have address the issues raised by the group to everyone's satisfaction. Please confirm that the I18N folks are satisfied with the changes, and thanks to all for helping to improve the spec!

**Comment by ianbjacobs** [comment]
Hi @aphillips and @xfq,

Thank you again for the review. We have completed merging all pull requests resulting from the review and thus I believe this issue can be closed. All the best,

Ian
