### ISSUE TITLE
RDF Dataset Canonicalization self review check

### ISSUE THREAD

**Issue by philarcher** [w3c/i18n-request#202]
### Name of your specification

RDF Dataset Canonicalization

### URL of your specification

https://www.w3.org/TR/rdf-canon/

### URL for your results

https://github.com/w3c/rdf-canon/issues/68

### Other comments

I hope I have filled in the request/self review sufficiently well. Please advise if not and I'll give it another shot.

**Comment by aphillips** [comment]
Hello @philarcher. Thank you for the self-review. I am the assigned reviewer and will comment directly on the self-review presently. Did you also mean to request an I18N review of the specification at this time? Do you have specific dates for progressing your spec that we can help you meet?
