### ISSUE TITLE
Compute Pressure API 2023-02-07 > 2023-03-31

### ISSUE THREAD

**Issue by anssiko** [w3c/i18n-request#204]
### Name of your specification

Compute Pressure API

### URL of your specification

https://www.w3.org/TR/compute-pressure/

### Do you need a reply by a particular date?

2023-03-31

### Please point to the results of your own self-review

https://github.com/w3c/compute-pressure/issues/184

### Where and how should the i18n WG raise issues?

https://github.com/w3c/compute-pressure/issues

### Pointer to any explainer for the spec

https://github.com/w3c/compute-pressure/blob/main/README.md

### Other comments

Thank you for your review and comments!

**Comment by xfq** [comment]
I have reviewed the spec and didn't found any issue. Closing.

**Comment by anssiko** [comment]
Thanks for your review!
