### ISSUE TITLE
Digital Publishing WAI-ARIA Module 1.1 and Digital Publishing Accessibility API Mappings 1.1 2023-02-23 > 2023-04-01

### ISSUE THREAD

**Issue by mattgarrish** [w3c/i18n-request#207]
### Name of your specification

Digital Publishing WAI-ARIA Module 1.1 and Digital Publishing Accessibility API Mappings 1.1

### URL of your specification

https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/ and https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/

### When does the review need to be finished?

Ideally for April, but there isn't a fixed timeline for moving to CR

### What has changed since any previous review?

Refer to the change logs for updates since the 1.0 release: https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#changelog and https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/#changelog

### Please point to the results of your own self-review

https://github.com/w3c/dpub-aria/issues/49

### Where and how should the i18n WG raise issues?

Please open issues for the DPUB-ARIA spec in https://github.com/w3c/dpub-aria/issues and issues for the DPUB-AAM in https://github.com/w3c/dpub-aam/issues

### Pointer to any explainer for the spec

https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#introduction

### Other comments

The DPUB-ARIA and AAM specs are modular extensions of ARIA and Core-AAM and only introduce new roles and mappings for publishing. As they don't introduce new attributes or technology, there shouldn't be issues that wouldn't need to be addressed in the parent specs.

**Comment by xfq** [comment]
I have reviewed the specs and didn't found any issue. Closing.

**Comment by mattgarrish** [comment]
Thanks @xfq!
