### ISSUE TITLE
Scalable Video Coding (SVC) Extension for WebRTC  2023-04-25 > 2023-05-16

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/i18n-request#210]
### Name of your specification

Scalable Video Coding (SVC) Extension for WebRTC

### URL of your specification

https://www.w3.org/TR/2023/WD-webrtc-svc-20230417/

### When does the review need to be finished?

May 16 2023

### What has changed since any previous review?

https://github.com/w3c/webrtc-svc/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E%3D2020-05-01+-label%3AEditorial+ - I don't think these change the results of the [previous I18N review](https://github.com/w3c/i18n-request/issues/112)

### Please point to the results of your own self-review

The spec has  no I18N intersection

### Where and how should the i18n WG raise issues?

https://github.com/w3c/webrtc-svc/issues

### Pointer to any explainer for the spec

https://github.com/w3c/webrtc-svc/blob/master/explainer.md

**Comment by xfq** [comment]
I have reviewed the spec and found no issues. Closing.
