### ISSUE TITLE
Verifiable Credentials Data Model v2.0 2023-06-15 > 2023-07-21?

### ISSUE THREAD

**Issue by awoie** [w3c/i18n-request#212]
### Name of your specification

Verifiable Credentials Data Model v2.0

### URL of your specification

https://www.w3.org/TR/vc-data-model-2.0/

### URL for your results

https://github.com/w3c/vc-data-model/issues/1155

**Comment by aphillips** [comment]
Thanks for the request! Do you have a specific date you need a response by? When are you planning a CR transition?

I have corrected the request date and proposed a due date of 21 July, but please advise if this is not soon enough.

**Comment by awoie** [comment]
> w3c/vc-data-model#1155

Thank you for your reply.

Relevant time constraints or deadlines: The VCWG is planning to take this specification to Candidate Recommendation in September 2023 (at W3C TPAC), reviews before that time frame (ideally, by the end of July 2023) would be ideal. So, 21 July should be fine.
