### ISSUE TITLE
Two issue templates has the same name

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-request#214]
There is two issue templates with name as 'Request review of a FPWD'.
- https://github.com/w3c/i18n-request/blob/gh-pages/.github/ISSUE_TEMPLATE/request-review-for-a-fpwd.yml
- https://github.com/w3c/i18n-request/blob/gh-pages/.github/ISSUE_TEMPLATE/request-fpwd-review.yml

After syntax error fixed by #213 , this conflict causes an error which leads not to show menu for FPWD review request at issue submission page. (Sorry, I've not checked the 'name' field, but only noticed about yaml syntax error...)
Diff between two issue templates are small (as below), and it seems `request-fpwd-review.yml` aligns with other templates.

@r12a @xfq  how about to remove `request-review-for-a-fpwd.yml`?

``` diff
request-review-for-a-fpwd.yml request-fpwd-review.yml
4c4
< labels: [ FPWD, "REVIEW REQUESTED", pending ]
---
> labels: [ "REVIEW REQUESTED", FPWD, pending ]
39c39
<       description: If so, add the date here
---
>       description: If any date, type here
41c41
<     id: self-review-issue
---
>     id: self
43,44c43,45
<       label: Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist).
<       description: If so, add the date here
---
>       label: Please point to the results of your own self-review
>       description: See https://w3c.github.io/i18n-drafts/techniques/shortchecklist.
>       placeholder: Link to the desired location
48,51c49,51
<       label: Where and how should the i18n WG raise issues? (We prefer to use the issue list in your document's repo.)
<       placeholder: Link to the location
<     validations:
<       required: true
---
>       label: Where and how should the i18n WG raise issues?
>       description: We prefer to use the issue list in your document's repo.
>       placeholder: Link to the desired location
53c53
<     id: self-explainer
---
>     id: explainer
55,56c55,56
<       label: Pointer to any explainer for the spec.
<       placeholder: Add a URL
---
>       label: Pointer to any explainer for the spec
>       placeholder: Add a URL.
```

**Comment by r12a** [comment]
I couldn't tell how to remove the option completely, but i disabled it by producing an error.  Now the button for "Request review of a FPWD" appears, but the duplicate doesn't at https://github.com/w3c/i18n-request/issues/new/choose

**Comment by himorin** [comment]
> I couldn't tell how to remove the option completely, 

opened a PR as https://github.com/w3c/i18n-request/pull/215
