### ISSUE TITLE
DAPT    2023-09-13

### ISSUE THREAD

**Issue by cconcolato** [w3c/i18n-request#217]
### Name of your specification

Dubbing and Audio description Profiles of TTML2

### URL of your specification

https://www.w3.org/TR/dapt/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### Do you need a reply by a particular date?

October, 31, 2023

### Please point to the results of your own self-review

https://github.com/w3c/dapt/wiki/Considerations-for-the-I18N-review

### Where and how should the i18n WG raise issues?

https://github.com/w3c/dapt/

### Pointer to any explainer for the spec

https://github.com/w3c/dapt/wiki/DAPT-Explained

**Comment by xfq** [comment]
We have reviewed the spec and found no issues. Closing.
