### ISSUE TITLE
W3C Securing Verifiable Credentials using JOSE and COSE 2023-09-18 > 2023-10-19

### ISSUE THREAD

**Issue by awoie** [w3c/i18n-request#218]
### Name of your specification

W3C Securing Verifiable Credentials using JOSE and COSE

### URL of your specification

https://www.w3.org/TR/vc-jose-cose/

### Does your specification include an Internationalization Considerations section?

- [X] My specification includes an Internationalization Considerations section

### URL for your results

https://github.com/w3c/vc-jose-cose/issues/95

### Do you need a reply by a particular date?

September

### Other comments

The W3C VCWG is approaching CR in October. We would kindly ask for a review in September if possible.

**Comment by thereisnogabe** [comment]
@aphillips can this be closed?

**Comment by aphillips** [comment]
Yes. I had moved it to completed, but not closed it yet. Thanks for the ping.
