### ISSUE TITLE
VC JSON Schema   2023-10-13> 2023-11-07

### ISSUE THREAD

**Issue by thereisnogabe** [w3c/i18n-request#220]
### Name of your specification

VC JSON Schema

### URL of your specification

https://w3.org/TR/vc-json-schema

### Does your specification include an Internationalization Considerations section?

- [X] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

2023-11-07

### What has changed since any previous review?

No previous reviews.

### Please point to the results of your own self-review

https://github.com/w3c/vc-json-schema/issues/164

### Where and how should the i18n WG raise issues?

https://github.com/w3c/vc-json-schema/issues

### Pointer to any explainer for the spec

https://github.com/w3c/vc-json-schema/blob/main/EXPLAINER.md

**Comment by himorin** [comment]
added https://github.com/w3c/vc-json-schema/issues/222

**Comment by aphillips** [comment]
added w3c/vc-json-schema#224 which caused me to remove the close label
