### ISSUE TITLE
BBS Cryptosuite v2023  2023-12-15 > 2023-01-15

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/i18n-request#221]
### Name of your specification

BBS Cryptosuite v2023 Securing Verifiable Credentials with Selective Disclosure using BBS Signatures

### URL of your specification

https://www.w3.org/TR/vc-di-bbs/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

2024-01-15

### What has changed since any previous review?

No previous review

### Please point to the results of your own self-review

https://github.com/w3c/vc-di-bbs/issues/103

### Where and how should the i18n WG raise issues?

https://github.com/w3c/vc-di-bbs/issues

### Pointer to any explainer for the spec

https://www.w3.org/TR/vc-di-bbs/#introduction

**Comment by aphillips** [comment]
(Issues pending I18N review are [here](https://github.com/w3c/i18n-activity/issues?q=is%3Aissue+is%3Aopen+label%3As%3Avc-di-bbs))
