### ISSUE TITLE
DeviceOrientation Event Specification 2024-01-29 > 2024-02-29

### ISSUE THREAD

**Issue by anssiko** [w3c/i18n-request#224]
### Name of your specification

DeviceOrientation Event Specification

### URL of your specification

https://www.w3.org/TR/orientation-event/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

2023-02-29

### What has changed since any previous review?

https://www.w3.org/TR/orientation-event/#changes

### Please point to the results of your own self-review

https://github.com/w3c/deviceorientation/issues/132

### Where and how should the i18n WG raise issues?

https://github.com/w3c/deviceorientation/issues

### Pointer to any explainer for the spec

https://w3c.github.io/motion-sensors/

### Other comments

This spec initially reached CR in August 2016 ([history](https://www.w3.org/standards/history/orientation-event/)) and was [retired in 2017](https://www.w3.org/TR/2017/NOTE-orientation-event-20170530/) due to the Geolocation WG closure. In 2019 DAS WG adopted this spec and during 2019-2024 made substantial interoperability, test automation, privacy and editorial improvements as outlined in the [changes](https://www.w3.org/TR/orientation-event/#changes) section.

These changes since the previous CR Snapshot from 2016 align the specification with widely available implementations, improve interoperability including testability, and add new features for enhanced privacy protections.

We did not consider any of the Internationalization Checklist topics directly relevant to the spec. We did leave some comments to our response you may want to review. Feedback on other than i18n aspects is also welcome.

Thank you for your internationalization review!

**Comment by himorin** [comment]
I found no item from i18n point of view, so I propose to mark this review request as completed without filing any i18n issue.

**Comment by aphillips** [comment]
Sounds good. I will move it now.

@anssiko We completed this review and found no issues. Good luck with your CR.

**Comment by anssiko** [comment]
@aphillips thanks for your swift response to this request!
