### ISSUE TITLE
CSS View Transitions 2 2024-04-03 > 2024-05-02

### ISSUE THREAD

**Issue by noamr** [w3c/i18n-request#230]
### Name of your specification

CSS View Transitions Level 2

### URL of your specification

https://drafts.csswg.org/css-view-transitions-2/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### Do you need a reply by a particular date?

No

### Please point to the results of your own self-review

https://github.com/WICG/view-transitions/blob/main/vt2-i18n-questionnaire.md

### Where and how should the i18n WG raise issues?

https://github.com/w3c/csswg-drafts/issues/new, with css-view-transitions-2 label

### Pointer to any explainer for the spec

https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md

**Comment by aphillips** [comment]
I reviewed this spec and did not find any apparent I18N issues.
