### ISSUE TITLE
Device Posture API 2024-05-31 > 2024-08-31

### ISSUE THREAD

**Issue by anssiko** [w3c/i18n-request#233]
### Name of your specification

Device Posture API

### URL of your specification

https://www.w3.org/TR/device-posture/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

 2024-08-31

### What has changed since any previous review?

This is the first i18n review request for this specification.

### Please point to the results of your own self-review

https://github.com/w3c/device-posture/issues/148

### Where and how should the i18n WG raise issues?

https://github.com/w3c/device-posture/issues/148

### Pointer to any explainer for the spec

https://github.com/w3c/device-posture/blob/gh-pages/README.md

### Other comments

For additional explainer material, see [Form Factors explainer](https://webscreens.github.io/form-factors/) for the broader domain and [Foldable APIs Origin Trial](https://developer.chrome.com/blog/foldable-apis-ot) for a developer-oriented explainer.

The Device Posture API is available as an [Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/4188910603407982593) from Chrome 125 until 128.

[foldable-devices/demos](https://github.com/foldable-devices/demos) hosts demos of various use cases for the API.

Thank you for your i18n review!

**Comment by himorin** [comment]
one submitted [issue resolved](https://github.com/w3c/i18n-activity/issues/1859) via [a PR approved by i18n](https://github.com/w3c/device-posture/pull/160).
