### ISSUE TITLE
Controllers Documents v1.0 2024-06-02 > 2024-09-02 

### ISSUE THREAD

**Issue by msporny** [w3c/i18n-request#234]
### Name of your specification

Controllers Documents v1.0

### URL of your specification

https://w3c.github.io/controller-document/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

2024-09-02

### What has changed since any previous review?

The Controller Documents v1.0 specification is a generalization of DID Documents and some content from VC Data Integrity. All this to say, horizontal review has occurred for most of this content before when it was in DID Core, and then again when it was in Verifiable Credential Data Integrity. The Working Group recently decided that it would rather have this content in a separate specification than embed it in DID Core or VC Data Integrity, and that specification is Controller Documents v1.0. 90%+ of the content remains the same as when it was reviewed previously before entering CR.

### Please point to the results of your own self-review

https://github.com/w3c/controller-document/issues/24

### Where and how should the i18n WG raise issues?

https://github.com/w3c/controller-document/issues/

### Pointer to any explainer for the spec

  - [DID Core Explainer](https://github.com/w3c/did-wg/blob/master/did-explainer.md)
  - [Data Integrity Explainer](https://github.com/w3c/vc-data-integrity/blob/main/EXPLAINER.md)
  - Let us know if you would like us to write another explainer for this spec: The spec is basically just "DID Documents, but you can now use other types of URLs in them (like HTTPS-based ones)". The spec exists so we can establish spec text, separate from DID Core and Data Integrity, that we can then normatively reference from other specs in the VCWG that don't have anything to do with DIDs, like generalized public key discovery algorithms.

### Other comments

It is unclear if i18n should spend much time on this specification since it's largely composed of text that has been reviewed by i18n multiple times over the past several years.

**Comment by himorin** [comment]
filed one issue on string match. I see no other.

**Comment by msporny** [comment]
> filed one issue on string match. I see no other.

Great, thank you @himorin! 

I don't see the issue yet, can you include a pointer to it here?

In any case, we will process the issue before going to CR.

**Comment by aphillips** [comment]
Completed. The issue found was non-I18N
