### ISSUE TITLE
Vibration API 2024-06-28 > 2024-09-20

### ISSUE THREAD

**Issue by anssiko** [w3c/i18n-request#236]
### Name of your specification

Vibration API

### URL of your specification

https://w3c.github.io/vibration/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

2024-09-20

### What has changed since any previous review?

Please see the [commit history](https://github.com/w3c/vibration/commits/gh-pages/) for details and the [changes section](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html#changes) for an overview of the changes since the latest published version. Diff between the [latest published version](https://www.w3.org/TR/2016/REC-vibration-20161018/) and the [staged snapshot](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html) is available at [htmldiff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FREC-vibration-20161018%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fw3c%252Fvibration%252Fchanges%252Findex.html).

### Please point to the results of your own self-review

https://github.com/w3c/vibration/issues/38

### Where and how should the i18n WG raise issues?

https://github.com/w3c/vibration/issues

### Pointer to any explainer for the spec

This feature predates the explainer era, but its MDN entry serves as a good starting point.

### Other comments

Due to complexity of revising a Recommendation under the old process, TR for this specification did not receive these latest updates informed by implementation experience, but they were incorporated into the Editor's Draft instead. This caused some unfortunate confusion among readers not closely watching the specification. To clear this confusion, supported by reinvigorated interest and process improvements for revising a Recommendation, this API is now being revived on the Recommendation Track to allow bringing the updates from the ED back to TR and to allow for further improvements using the modern streamlined publication flow.

Thank you for your review!

**Comment by aphillips** [comment]
Review completed: we did not find any I18N issues. Thank you!

**Comment by anssiko** [comment]
Thank you for you review!
