### ISSUE TITLE
Incremental Font Transfer   2024-07-09 > 2024-10-17?

### ISSUE THREAD

**Issue by svgeesus** [w3c/i18n-request#238]
### Name of your specification

Incremental Font Transfer

### URL of your specification

https://www.w3.org/TR/2024/WD-IFT-20240709/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### Do you need a reply by a particular date?

No

### Please point to the results of your own self-review

https://github.com/w3c/IFT/issues/195

### Where and how should the i18n WG raise issues?

https://github.com/w3c/IFT

### Pointer to any explainer for the spec

https://github.com/w3c/IFT/blob/main/IFT-Explainer.md

### Other comments

In terms of I18n capabilities there is no functional gain or loss compared to earlier drafts. 

Just that the current proposal is more likely to be widely implemented, which will be of particular benefit for scripts involving large character repertoires. Of course, further review from an I18n perspective is warmly invited.

**Comment by aphillips** [comment]
Added an artificial end date. Most likely this review will be completed prior to TPAC.

**Comment by himorin** [comment]
See no issue from i18n handling point of view. 

One minor point I would consult with i18n is mixing use of `code point(s)` and `codepoint(s)`. Former should be our desire per glossary, but both are used in the document, such as [`codepoints` in section 3.1](https://www.w3.org/TR/2024/WD-IFT-20240709/#font-subset-dfn) or [`code points` in section 5.2.1.1](https://www.w3.org/TR/2024/WD-IFT-20240709/#interpreting-patch-map-format-1) (or detailed per step processing definitions). Should we point this?
(note, there is one parameter in structure named as [`codepoints`](https://www.w3.org/TR/2024/WD-IFT-20240709/#mapping-entry-codepoints), so some of these are correct as referencing that)

**Comment by svgeesus** [comment]
@himorin thanks for raising his, we have [corrected](https://github.com/w3c/IFT/pull/202) the specification to use `code point(s)` consistently. The parameter has been renamed `codePoints`.
