### ISSUE TITLE
TTML2 > ~2016-12-31

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-request#24]
https://github.com/w3c/i18n-activity/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3As%3Attml

https://w3c.github.io/ttml2/spec/ttml2.html

Issues:
https://github.com/w3c/i18n-activity/labels/ttml

**Comment by aphillips** [comment]
There are six open issues against TTML2 filed in January of 2020. Each of these appears to have been deferred by the TTML working group to a future version 3. I propose that we close this review as "completed" and review TTML3 as it emerged. Our tracking issues are intact for that purpose.
