### ISSUE TITLE
Picture in Picture 2024-10-24 > 2025-01-31

### ISSUE THREAD

**Issue by chrisn** [w3c/i18n-request#244]
### Name of your specification

Picture in Picture

### URL of your specification

https://www.w3.org/TR/picture-in-picture/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

31 Jan 2025

### What has changed since any previous review?

No previous review.

### Please point to the results of your own self-review

https://github.com/w3c/picture-in-picture/issues/236

### Where and how should the i18n WG raise issues?

https://github.com/w3c/picture-in-picture/issues

### Pointer to any explainer for the spec

https://github.com/w3c/picture-in-picture/blob/main/explainer.md

**Comment by himorin** [comment]
Found no issue from i18n point of view. So, propose to close this with completed.
No natural string related definition, while one string parameter defined but used as an enum typed.
