### ISSUE TITLE
DAPT  2024-11-06 > 2024-12-05

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-request#247]
### Name of your specification

DAPT (Dubbing and Audio description Profiles of TTML2)

### URL of your specification

https://www.w3.org/TR/dapt/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

ASAP, by mid-December at the latest

### What has changed since any previous review?

See below.

### Other comments

The Timed-Text WG has requested i18n horizontal review [1] of the DAPT specification [2] last year and passed. After since, WG has tried to settle down remaining issues to make clarify and better metadata structuring, and recently we could reach to consensus to request the DAPT specification as CRS with marking several items as at-risk [3 and threads].

*1 https://github.com/w3c/i18n-request/issues/217 (req 2023-09-13, closed 2023-09-29)
*2 https://www.w3.org/TR/dapt/ (under streamlined publication)
*3 https://lists.w3.org/Archives/Public/public-tt/2024Oct/0004.html (summary of changes are listed at later part of this email)

I believe most of changes listed in [3] or summary of substantive changes [4] are fine per i18n, but could you kindly check two sections specifically - somehow related to language?
- 4.1.1 Script Represents : https://www.w3.org/TR/dapt/#script-represents
- 4.1.2 Default Language : https://www.w3.org/TR/dapt/#default-language

*4 https://www.w3.org/TR/dapt/substantive-changes-summary.txt

Once we got ok from i18n, we would submit a transition request to CRS of this DAPT specification.

**Comment by xfq** [comment]
I reviewed the document and found no issues related to i18n.
