### ISSUE TITLE
Internationalized Domain Names in Applications (IDNA): Registry Restrictions and Recommendations 2024-12-04 > 2025-02-04

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-request#252]
### Name of your specification

Internationalized Domain Names in Applications (IDNA): Registry Restrictions and Recommendations

### URL of your specification

https://datatracker.ietf.org/doc/draft-klensin-idna-rfc5891bis/

### Does your specification include an Internationalization Considerations section?

- [ ] My specification includes an Internationalization Considerations section

### When does the review need to be finished?

N/A

### Where and how should the i18n WG raise issues?

Comments go to the authors ([john-ietf@jck.com](mailto:john-ietf@jck.com) and [asmus@unicode.org](mailto:asmus@unicode.org)), [art@ietf.org](mailto:art@ietf.org), and the IESG ([iesg@ietf.org](mailto:iesg@ietf.org)).

**Comment by xfq** [comment]
I have reviewed this document and didn't find any issues.

The profitability of domain names and the decision-making and responsibilities of registries were discussed, and there were no changes to the IDNA protocols. Security issues and additional contextual rules by zones were also discussed.

There are also some errata about Unicode in this document. They look good to me.

**Comment by aphillips** [comment]
Completed, no issues found, @xfq to write to mnot/et al and jck to notify
